spring:
  application:
    name: flag-delivery-mono
  data:
    jdbc:
      dialect: postgresql
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: test



login:
  url: "/api/v1/auth/signin"

token:
  secret: somereallyreallylongkeythatisokayfortheshaalgorithm
  expiration-time: 86400000

logging:
  level:
    org.springframework.security: TRACE