databaseChangeLog:
  - changeSet:
      id: 2025-09-26-create-environment-flag-config-table
      author: urninax
      changes:
        - createTable:
            tableName: environment_flag_config
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    nullable: false
                    primaryKeyName: pk_flag_config
                    primaryKey: true
              - column:
                  name: environment_id
                  type: uuid
                  constraints:
                    nullable: false
                    foreignKeyName: fk_flag_config_environment
                    deleteCascade: true
                    references: environment(id)
              - column:
                  name: flag_id
                  type: uuid
                  constraints:
                    foreignKeyName: fk_flag_config_flag
                    nullable: false
                    deleteCascade: true
                    references: feature_flag(id)
              - column:
                  name: is_on
                  type: boolean
                  defaultValueBoolean: false
                  constraints:
                    nullable: false
              - column:
                  name: salt
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: sel
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: archived
                  type: boolean
                  defaultValueBoolean: false
              - column:
                  name: on_variation_id
                  type: uuid
                  constraints:
                    foreignKeyName: fk_flag_config_on_variation
                    nullable: false
                    references: flag_variation(id)
              - column:
                  name: off_variation_id
                  type: uuid
                  constraints:
                    foreignKeyName: fk_flag_config_off_variation
                    nullable: false
                    references: flag_variation(id)
              - column:
                  name: fallthrough_variation_id
                  type: uuid
                  constraints:
                    foreignKeyName: fk_flag_config_fallthrough_variation
                    nullable: false
                    references: flag_variation(id)
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: version
                  type: bigint
                  defaultValueNumeric: "1"
                  constraints:
                    nullable: false
        - addUniqueConstraint:
            tableName: environment_flag_config
            columnNames: environment_id, flag_id
            constraintName: ux_flag_config_environment_flag
        - createIndex:
            tableName: environment_flag_config
            columns:
              - column:
                  name: flag_id
            indexName: idx_env_flag_config_flag

      rollback:
        - dropIndex:
            tableName: environment_flag_config
            indexName: idx_env_flag_config_flag

        - dropUniqueConstraint:
            tableName: environment_flag_config
            constraintName: ux_flag_config_environment_flag

        - dropTable:
            tableName: environment_flag_config
            cascadeConstraints: true