databaseChangeLog:
  - changeSet:
      id: 2025-09-25-environment-add-critical-column
      author: urninax
      logicalFilePath: db/changelog/environment-critical.yaml
      changes:
        - addColumn:
            tableName: environment
            columns:
              - column:
                  name: critical
                  type: boolean
                  defaultValueBoolean: false
                  constraints:
                    nullable: false

      rollback:
        - dropColumn:
            columnName: critical
            tableName: environment